name: Monthly IMDb Update of Must-See list

on:
  schedule:
    - cron: '0 0 1 * *' # Every month
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download movies.csv from Google Drive
        env:
          MOVIES_FILE_ID: ${{ secrets.MOVIES_FILE_ID }}
        run: |
          # Use gdown to download the file using the ID from your secrets
          python -m gdown --id $MOVIES_FILE_ID -O movies.csv

      - name: Run Script
        env:
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
        run: python metacritic_must_see.py

      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-data
          path: movies-update.log
